#!/bin/bash
INFO_HEADER="<ESC> Exit, <PgUp> Preview up, <PgDown> Preview down"
FZF_OPTS=("--layout=reverse-list" "--no-height" "--multi" "--bind" "pgdn:preview-down" "--bind" "pgup:preview-up" "--header" "$INFO_HEADER")
SUDO_CMD=$(command -v sudo)

root_check() {
    if [[ $EUID -ne 0 ]]; then
        if ! command -v sudo &>/dev/null; then
            echo "You need to be root or use sudo to continue"
            exit 1
        fi
    fi
}

get_installed_pkgs() {
    dpkg-query --show --showformat='${Package} ${db:Status-Status}\n' | grep installed | awk '{print $1}'
}

fzf_apt_install() {
    local installed_pkg
    local all_pkg

    root_check

    $SUDO_CMD apt-get update

    installed_pkg=$(get_installed_pkgs)
    all_pkg=$(apt-cache pkgnames)

    echo "$installed_pkg" "$all_pkg" | tr ' ' '\n' | sort | uniq -u | fzf "${FZF_OPTS[@]}" --preview='apt-cache show {}' --prompt='Install packages > ' --bind "enter:execute($SUDO_CMD apt-get install -y {+})+accept"
}

fzf_apt_cleanpurge() {
    fzf_apt_purge && $SUDO_CMD apt-get autoremove
}

fzf_apt_remove() {
    root_check
    local selection
    selection=$(get_installed_pkgs | fzf "${FZF_OPTS[@]}" --preview='dpkg-query -s {}' --prompt='Uninstall packages > ')
    if [[ -n "$selection" ]]; then
        echo "$selection" | tr '\n' ' ' | xargs "$SUDO_CMD" apt-get remove -y 
    fi
}

fzf_apt_purge() {
    root_check
    local selection
    selection=$(get_installed_pkgs | fzf "${FZF_OPTS[@]}" --preview='dpkg-query -s {}' --prompt='Uninstall packages > ')
    if [[ -n "$selection" ]]; then
        echo "$selection" | tr '\n' ' ' | xargs "$SUDO_CMD" apt-get purge -y 
    fi
}

fzf_apt_list() {
    get_installed_pkgs | fzf --preview='dpkg-query -s {}' --prompt='Installed packages list > '
}

fzf_apt_upgrade() {
    root_check
    $SUDO_CMD apt-get update && $SUDO_CMD apt-get dist-upgrade
}

fzf_apt_cleanupgrade() {
    fzf_apt_upgrade && $SUDO_CMD apt-get autoremove
}

case $1 in
install)
    fzf_apt_install $2
    ;;
purge)
    fzf_apt_purge $2
    ;;
purge+autoremove)
    fzf_apt_cleanpurge $2
    ;;
list)
    fzf_apt_list
    ;;
upgrade)
    fzf_apt_upgrade $2
    ;;
remove)
    fzf_apt_remove $2
    ;;
upgrade+autoremove)
    fzf_apt_cleanupgrade $2
    ;;
*)
    echo "Unknown action $1"
    echo 'Usage: fzf-dpkg (install | purge | remove | list | upgrade | purge+autoremove | upgrade+autoremove) [-y]'
    ;;
esac
