#!/bin/bash

export FZF_DEFAULT_OPTS="--exact --border --cycle --multi --layout=reverse-list $FZF_DEFAULT_OPTS"
SUDO_CMD=$(command -v sudo)

root_check() {
    if [[ $EUID -ne 0 ]]; then
        if ! command -v sudo &>/dev/null; then
            echo "You need to be root or use sudo to continue"
            exit 1
        fi
    fi
}

get_installed_pkgs() {
    dpkg-query --show --showformat='${Package} ${db:Status-Status}\n' | grep installed | awk '{print $1}'
}

fzf_apt_install() {
    root_check
    $SUDO_CMD apt-get update
    local installed_pkg=get_installed_pkgs
    local all_pkg=$(apt-cache pkgnames)
    local selection=$(awk '{ h[$0] = ! h[$0] } END { for (k in h) if (h[k]) print k }' <(echo "$installed_pkg") <(echo "$all_pkg") | fzf --preview='apt-cache show {}' --header='Uninstall packages. <Tab> = Select multiple packages. <Enter> = Install one or more packages. <ESC> = Exit')
    if [[ -n "$selection" ]]; then
        $SUDO_CMD apt-get install $selection
    fi
}

fzf_apt_cleanpurge() {
    fzf_apt_purge && $SUDO_CMD apt-get autoremove
}

fzf_apt_purge() {
    root_check
    get_installed_pkgs | fzf --preview='dpkg-query -s {}' --header='Uninstall packages. <Tab> = Select multiple packages. <Enter> = Uninstall one or more packages. <ESC> = Exit'
    if [[ -n "$selection" ]]; then
        $SUDO_CMD apt-get purge $selection
    fi
}

fzf_apt_list() {
    get_installed_pkgs | fzf --preview='dpkg-query -s {}' --header='Installed packages list. <ESC> = Exit'
}

fzf_apt_upgrade() {
    root_check
    $SUDO_CMD apt-get update && $SUDO_CMD apt-get dist-upgrade
}

fzf_apt_cleanupgrade() {
    fzf_apt_upgrade && $SUDO_CMD apt-get autoremove
}

case $1 in
install)
    fzf_apt_install
    ;;
purge)
    fzf_apt_purge
    ;;
purge-clean)
    fzf_apt_cleanpurge
    ;;
list)
    fzf_apt_list
    ;;
upgrade)
    fzf_apt_upgrade
    ;;
upgrade-clean)
    fzf_apt_cleanupgrade
    ;;
*)
    echo "Unknown action $1"
    echo 'Usage: fzf-dpkg (install | purge | purge-clean | list | upgrade | upgrade-clean)'
    ;;
esac
